name: CI 
on: 
  push: 
    branches:
      - main
      - 'feature/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: rustup component add rustfmt    
      # - run: cargo fmt --manifest-path Cargo.toml -- --check
      - run: cargo fmt --manifest-path Cargo.toml -- --diff
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
      - run: rustc --version 
      - run: cargo build
      - run: cargo test

