name: CI 
on: 
  push: 
    branches:
      - feature/ci

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: rustc --version 
      - run: cargo test

