name: CI 
on: 
  push: 
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pull-requests: write
  actions: read
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: rustup component add rustfmt    
      - run: cargo fmt --manifest-path Cargo.toml -- 
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
      - run: rustc --version 
      - run: cargo build
      - run: cargo test

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.ref, 'refs/heads/release') 
    steps: 
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --release
      - name: Create Github release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
      - name: Git tag version 
        uses: pkgdeps/git-tag-action@v3
        with:
          version: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          git_tag_prefix: ${{ github.ref_name }}
          git_commit_sha: ${{ github.sha }}
          github_repo: ${{ github.repository }}
